"""Report evidence-backed readiness for public transcripts and summaries.

This deliberately reports coverage and verification separately.  A transcript
that exists is searchable, but it is not automatically an audio-verified
transcript; a non-template summary is not automatically an editorially
approved summary.  The report is small enough to commit and regenerate during
the long-running review process.
"""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
import gzip
import json
from pathlib import Path
from typing import Any

from content_quality import is_publishable_summary

ROOT = Path(__file__).resolve().parent
CATALOG = ROOT / "public" / "catalog.json"
PROCESSING = ROOT / "data" / "processing_manifest.json"
AUDIT = ROOT / "data" / "transcript_paragraph_audit.json.gz"
REVIEWS = ROOT / "data" / "transcript_audio_reviews.json"
EVALUATION = ROOT / "data" / "transcript_review_evaluation.json"
OUTPUT = ROOT / "data" / "quality_baseline.json"
REQUIRED_MODELS = ("small", "medium", "large-v3")

# These strings were generated by the former template system.  They may be
# grammatically fine, but they are not evidence-backed summaries of a video.
GENERIC_SUMMARY_MARKERS = (
    "整理設定選擇、拍攝條件與實作判斷。",
    "分享攝影、器材或創作上的觀察與經驗。",
    "分享現場觀察與取景思考。",
)


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def catalog_videos(catalog: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        video
        for category in catalog.get("categories", [])
        for video in category.get("videos", [])
    ]


def is_generic_summary(summary: str) -> bool:
    return any(marker in (summary or "") for marker in GENERIC_SUMMARY_MARKERS)


def build_report(
    catalog: dict[str, Any],
    processing: dict[str, Any],
    audit: dict[str, Any],
    reviews: dict[str, Any],
    evaluation: dict[str, Any],
) -> dict[str, Any]:
    videos = catalog_videos(catalog)
    paragraphs = audit.get("paragraphs", [])
    review_items = list(reviews.values())
    decisions = evaluation.get("decisions", {})

    summaries = [str(video.get("ai_summary", "")) for video in videos]
    approved_summaries = sum(
        is_publishable_summary(summary, str(video.get("title", "")))
        for video, summary in zip(videos, summaries, strict=True)
    )
    all_models = sum(
        all(model in review.get("asr", {}) for model in REQUIRED_MODELS)
        for review in review_items
    )
    any_model = sum(bool(review.get("asr")) for review in review_items)
    historically_unavailable = sum(review.get("audio_status") == "unavailable" for review in review_items)

    return {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "public_video_text": {
            "catalog_videos": len(videos),
            "approved_evidence_backed_summaries": approved_summaries,
            "generic_template_summaries": sum(is_generic_summary(summary) for summary in summaries),
            "requires_curated_summary": len(videos) - approved_summaries,
        },
        "transcript_coverage": {
            "catalog_videos": len(videos),
            "complete": int(processing.get("counts", {}).get("complete", 0)),
            "no_transcript_expected": int(processing.get("counts", {}).get("no_transcript_expected", 0)),
            "paragraphs": len(paragraphs),
        },
        "audio_review": {
            "flagged_paragraphs": sum(bool(paragraph.get("needs_audio_review")) for paragraph in paragraphs),
            "candidate_corrections": sum(
                paragraph.get("raw_text") != paragraph.get("candidate_text")
                for paragraph in paragraphs
            ),
            "review_records": len(review_items),
            "reviewed_with_any_model": any_model,
            "reviewed_with_all_required_models": all_models,
            "historically_marked_audio_unavailable": historically_unavailable,
            "decision_statuses": dict(sorted(Counter(
                str(decision.get("status", "unknown")) for decision in decisions.values()
            ).items())),
        },
        "quality_gate": {
            "transcripts_ready_for_95_percent_claim": False,
            "summaries_ready_for_95_percent_claim": False,
            "reason": "Only explicit audio and editorial verification may enable a confidence claim.",
        },
    }


def read_report_inputs() -> tuple[dict[str, Any], dict[str, Any], dict[str, Any], dict[str, Any], dict[str, Any]]:
    with gzip.open(AUDIT, "rt", encoding="utf-8") as handle:
        audit = json.load(handle)
    return (
        load_json(CATALOG, {}),
        load_json(PROCESSING, {}),
        audit,
        load_json(REVIEWS, {}),
        load_json(EVALUATION, {}),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Report transcript and summary quality readiness.")
    parser.add_argument("--write", action="store_true", help="Write data/quality_baseline.json as well as printing it.")
    args = parser.parse_args()
    report = build_report(*read_report_inputs())
    if args.write:
        OUTPUT.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
